Question 3)

In [208]:
import numpy as np
from qutip import *

a) Alice 

In [209]:
def Alice(bits):
    events = []
    
    for i in range (1, bits+1):
        photon = np.random.choice([0, 1])
        
        if photon == 0:
            polar_state = basis(2, photon)
        else: 
            polar_state = (1/np.sqrt(2))*(basis(2,0)+basis(2,1))
        events.append((i,polar_state))
        
    return events


bits = 5
alice_events = Alice(bits)

for index, state in alice_events:
    print(f"Event {index}: {state}")

Event 1: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]
Event 2: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]
Event 3: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]
Event 4: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]
Event 5: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]


b) Bob

In [451]:

def Alice(bits):
    events = []
    
    for i in range (1, bits+1):
        photon = np.random.choice([0, 1])
        
        if photon == 0:
            polar_state = basis(2, photon)
        else: 
            polar_state = (1/np.sqrt(2))*(basis(2,0)+basis(2,1))
        events.append((i,polar_state))
        
    return events

def bob(alice_output):
    detected_events = []
    for event in alice_output:
        index, photon_state = event
        
        # Bob measures with either |↕⟩ (vertical) or |⤡⟩ (diagonal)
        measurement_basis = np.random.choice([0, 1])
        if measurement_basis == 0:
            bob_measurement = basis(2, measurement_basis)  # |↕⟩ in H/V basis
        else:
            bob_polar_state = (1/np.sqrt(2))*(basis(2, 0)- basis(2, 1))  # |⤡⟩ in H/V basis
        
        # Compute the probability of detection
        probability_of_detection = abs((photon_state.dag() * bob_measurement).full()[0, 0]) ** 2
        
        # Simulate the detection event
        detection_event = np.random.choice([True, False], p=[probability_of_detection, 1 - probability_of_detection])
        
        # If Bob detects a photon, record the result
        if detection_event:
            detected_events.append([index, int(measurement_basis == 'diagonal')])
    
    return detected_events

# Example usage
Np = 10  # Number of photons
alice_output = Alice(bits)
bob_output = bob(alice_output)

# Print the results
print("Alice's Output:")
print("Index\tPhoton State")
for event in alice_output:
    print(f"{event[0]}\t{event[1]}")

print("\nBob's Output:")
print("Index\tBob's Guess")
for event in bob_output:
    print(f"{event[0]}\t{event[1]}")


Alice's Output:
Index	Photon State
1	Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]
2	Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]
3	Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]
4	Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]
5	Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]

Bob's Output:
Index	Bob's Guess
1	0
2	0
3	0
4	0


c) 

In [471]:

def bob(alice_output):
    detected_events = []
    for event in alice_output:
        index, photon_state = event
        
        # Bob measures with either |↕⟩ (vertical) or |⤡⟩ (diagonal)
        measurement_basis = np.random.choice([0, 1])
        if measurement_basis == 0:
            bob_measurement = basis(2, measurement_basis)  # |↕⟩ in H/V basis
        else:
            bob_polar_state = (1/np.sqrt(2))*(basis(2, 0)- basis(2, 1))  # |⤡⟩ in H/V basis
        
        
        # Compute the probability of detection
        probability_of_detection = abs((photon_state.dag() * bob_measurement).full()[0, 0]) ** 2
        
        # Simulate the detection event
        detection_event = np.random.choice([True, False], p=[probability_of_detection, 1 - probability_of_detection])
        
        # If Bob detects a photon, record the result
        if detection_event:
            detected_events.append([index, int(measurement_basis == 'diagonal')])
    
    return detected_events

# Example usage
Np = 10  # Number of photons
alice_output = Alice(bits)
bob_output = bob(alice_output)

# Print results
print("Alice's output:")
for event in alice_output:
    print(f"Event {event[0]}: {event[1]}")

print("\nBob's detected events:")
for event in bob_output:
    print(f"Event {event[0]}: Bob thinks Alice sent bit {event[1]}")


Alice's output:
Event 1: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]
Event 2: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]
Event 3: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]
Event 4: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]
Event 5: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]

Bob's detected events:
Event 1: Bob thinks Alice sent bit 0
Event 2: Bob thinks Alice sent bit 0
Event 3: Bob thinks Alice sent bit 0
Event 4: Bob thinks Alice sent bit 0


d)

In [529]:
def Eve(events):
    results = []
    for event in events:
        index, state = event
        # Eve performs the same measurement as Bob
        eve_measurement_basis = bob_measurement_basis
        #if measurement_basis == 0:
        #    eve_measurement = basis(2, measurement_basis)  # |↕⟩ in H/V basis
        #else:
        #    evepolar_state = (1/np.sqrt(2))*(basis(2, 0)- basis(2, 1))  # |⤡⟩ in H/V basis
        
        measurement = state.measure([basis(2, 0), basis(2, 1)])
        # Eve makes her best guess based on the measurement
        if measurement[0] == 1:
            guessed_state = basis(2, 0)
        elif measurement[1] == 1:
            guessed_state = basis(2, 1)
        results.append([index, guessed_state])
        print(results)
    return results

In [473]:
#def Eve(events):
#    results = []
#    for event in events:
#        index, state = event
#        # Eve performs the same measurement as Bob
#        measurement_basis = np.random.choice([0, 1])
#        if measurement_basis == 0:
#            bob_measurement = basis(2, measurement_basis)  # |↕⟩ in H/V basis
#        else:
#            polar_state = (1/np.sqrt(2))*(basis(2, 0)- basis(2, 1)) 
#        measurement = expect([bob_measurement, polar_state, state)
#        ## Eve makes her best guess based on the measurement
#        #if measurement[0] == 1:
#        #    guessed_state = basis(2, 0)
#        #elif measurement[1] == 1:
#        #    guessed_state = basis(2, 1)
#        results.append([index, guessed_state])
#    return results
#

e)

In [476]:
Np = 100

# Alice sends photons to Bob through the channel
alice_events = Alice(bits)

# Bob receives and measures the photons
bob_output = bob(alice_events)

# Alice and Bob use half of the events for verification
verification_size = Np // 2
alice_verify = alice_events[:verification_size]
bob_verify = bob_output[:verification_size]

# Count the number of errors in the verification process
error_count = sum(1 for a, b in zip(alice_verify, bob_verify) if a[1] != b[1])

# Calculate the error rate
error_rate = error_count / verification_size

print("Error Rate:", error_rate)


Error Rate: 0.06


f)

In [494]:
Np = 1000

# Alice sends photons to Bob through the channel
alice_events = Alice(bits)

# Bob receives and measures the photons
bob_output = bob(alice_events)

# Alice and Bob use half of the events for verification
verification_size = Np // 2
alice_verify = alice_events[:verification_size]
bob_verify = bob_output[:verification_size]

# Count the number of errors in the verification process
error_count = sum(1 for a, b in zip(alice_verify, bob_verify) if a[1] != b[1])

# Calculate the error rate
error_rate = error_count / verification_size

print("Error Rate:", error_rate)


Error Rate: 0.01
