Question 3)

In [2]:
import numpy as np
from qutip import *

a) Alice 

In [3]:


def Alice(N_p):
    events = []

    for i in range(1, N_p + 1):
        # Randomly choose 0 or 1 with equal probability
        bit_to_send = np.random.choice([0, 1])

        # Create a quantum object representing the photon state
        photon_state = basis(2, bit_to_send)

        # Append the event as a tuple (index, photon_state) to the events list
        events.append((i, Qobj(photon_state)))

    return events

# Example usage:
N_p = 5  # Number of bits (photons) to send
alice_events = Alice(N_p)

# Display the results
for index, state in alice_events:
    print(f"Event {index}: {state}")


Event 1: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]
Event 2: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]
Event 3: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]
Event 4: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]
Event 5: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]


b) Bob

In [4]:

def alice(Np):
    events = []
    for i in range(1, Np + 1):
        # Choose randomly between 0 and 1 with equal probability
        bit_to_send = np.random.choice([0, 1])
        
        # Create the corresponding quantum object
        if bit_to_send == 0:
            photon_state = qt.basis(2, 0)  # |↔⟩ in H/V basis
        else:
            photon_state = qt.basis(2, 1)  # |⤢⟩ in H/V basis
        
        events.append([i, photon_state])
    
    return events

def bob(alice_output):
    detected_events = []
    for event in alice_output:
        index, photon_state = event
        
        # Bob measures with either |↕⟩ (vertical) or |⤡⟩ (diagonal)
        measurement_basis = np.random.choice(['vertical', 'diagonal'])
        if measurement_basis == 'vertical':
            bob_measurement = qt.basis(2, 0)  # |↕⟩ in H/V basis
        else:
            bob_measurement = qt.basis(2, 1)  # |⤡⟩ in H/V basis
        
        # Compute the probability of detection
        probability_of_detection = abs((photon_state.dag() * bob_measurement).full()[0, 0]) ** 2
        
        # Simulate the detection event
        detection_event = np.random.choice([True, False], p=[probability_of_detection, 1 - probability_of_detection])
        
        # If Bob detects a photon, record the result
        if detection_event:
            detected_events.append([index, int(measurement_basis == 'diagonal')])
    
    return detected_events

# Example usage
Np = 10  # Number of photons
alice_output = alice(Np)
bob_output = bob(alice_output)

# Print the results
print("Alice's Output:")
print("Index\tPhoton State")
for event in alice_output:
    print(f"{event[0]}\t{event[1]}")

print("\nBob's Output:")
print("Index\tBob's Guess")
for event in bob_output:
    print(f"{event[0]}\t{event[1]}")


NameError: name 'qt' is not defined

In [ ]:
def alice_and_bob(Np):
    detected_events = []
    for idx in range(1, Np+1):
        # Alice: Randomly choose bit to send (0 or 1)
        sent_bit = np.random.choice([0, 1])
        
        # Alice: Convert bit to polarization state
        if sent_bit == 0:
            photon_state = basis(2, 0)  # |↔⟩ (H polarization)
        else:
            photon_state = basis(2, 1)  # |⤢⟩ (V polarization)
        
        # Bob: Randomly choose between |↕⟩ (vertical polarizer) and |⤡⟩ (diagonal polarizer)
        bob_polarizer = basis(2, np.random.choice([0, 1]))
        
        # Combine Alice and Bob actions
        combined_state = tensor(photon_state, bob_polarizer)
        
        # Measure the combined state
        measurement = expect(ptrace(composite(combined_state), [0]), photon_state)
        
        # If there is a click, Bob knows the sent bit
        if measurement > 0.5:
            detected_events.append([idx, int(bob_polarizer[1, 0])])

    return detected_events

# Example usage
Np = 10  # Number of photons
combined_output = alice_and_bob(Np)

# Print results
print("Combined output:")
for event in combined_output:
    print(f"Event {event[0]}: Alice sent bit {event[1]}, Bob thinks Alice sent bit {event[1]}")


Combined output:
Event 1: Alice sent bit 0, Bob thinks Alice sent bit 0
Event 2: Alice sent bit 0, Bob thinks Alice sent bit 0
Event 3: Alice sent bit 0, Bob thinks Alice sent bit 0
Event 4: Alice sent bit 0, Bob thinks Alice sent bit 0
Event 5: Alice sent bit 1, Bob thinks Alice sent bit 1
Event 6: Alice sent bit 0, Bob thinks Alice sent bit 0
Event 7: Alice sent bit 0, Bob thinks Alice sent bit 0
Event 8: Alice sent bit 1, Bob thinks Alice sent bit 1
Event 9: Alice sent bit 0, Bob thinks Alice sent bit 0
Event 10: Alice sent bit 1, Bob thinks Alice sent bit 1


/var/folders/z3/5wtht_qx4ylbrx748h07ps780000gn/T/ipykernel_78368/1845033813.py:24: ComplexWarning: Casting complex values to real discards the imaginary part
  detected_events.append([idx, int(bob_polarizer[1, 0])])


c) 

In [ ]:
import numpy as np
from qutip import *

def bob(alice_output):
    detected_events = []
    for idx, photon_state in alice_output:
        # Bob: Randomly choose between |↕⟩ (vertical polarizer) and |⤡⟩ (diagonal polarizer)
        bob_polarizer = basis(2, np.random.choice([0, 1]))
        
        # Combine Alice and Bob actions
        combined_state = tensor(photon_state, bob_polarizer)
        
        # Measure the combined state
        measurement = expect(ptrace(composite(combined_state), [0]), photon_state)
        
        # If there is a click, Bob knows the sent bit
        if measurement > 0.5:
            detected_events.append([idx, int(bob_polarizer[1, 0])])

    return detected_events

# Example usage
Np = 10  # Number of photons
alice_output = alice(Np)
bob_output = bob(alice_output)

# Print results
print("Alice's output:")
for event in alice_output:
    print(f"Event {event[0]}: {event[1]}")

print("\nBob's detected events:")
for event in bob_output:
    print(f"Event {event[0]}: Bob thinks Alice sent bit {event[1]}")


Alice's output:
Event 1: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]
Event 2: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]
Event 3: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]
Event 4: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]
Event 5: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]
Event 6: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]
Event 7: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]
Event 8: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]
Event 9: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]
Event 10: Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]

Bob's detected events:

/var/folders/z3/5wtht_qx4ylbrx748h07ps780000gn/T/ipykernel_78368/1150100772.py:18: ComplexWarning: Casting complex values to real discards the imaginary part
  detected_events.append([idx, int(bob_polarizer[1, 0])])


d)

In [ ]:
def Eve(events):
    results = []
    for event in events:
        index, state = event
        # Eve performs the same measurement as Bob
        measurement = state.measure([qt.basis(2, 0), qt.basis(2, 1)])
        # Eve makes her best guess based on the measurement
        if measurement[0] == 1:
            guessed_state = qt.basis(2, 0)
        elif measurement[1] == 1:
            guessed_state = qt.basis(2, 1)
        results.append([index, guessed_state])
        print(results)
    return results

In [ ]:
def Eve(events):
    results = []
    for event in events:
        index, state = event
        # Eve performs the same measurement as Bob
        measurement = qt.expect([qt.basis(2, 0), qt.basis(2, 1)], state)
        # Eve makes her best guess based on the measurement
        if measurement[0] == 1:
            guessed_state = qt.basis(2, 0)
        elif measurement[1] == 1:
            guessed_state = qt.basis(2, 1)
        results.append([index, guessed_state])
    return results


e)

In [14]:
Np = 100

# Alice sends photons to Bob through the channel
alice_events = Alice(Np)

# Bob receives and measures the photons
bob_output = Bob(alice_events)

# Alice and Bob use half of the events for verification
verification_size = Np // 2
alice_verify = alice_events[:verification_size]
bob_verify = bob_output[:verification_size]

# Count the number of errors in the verification process
error_count = sum(1 for a, b in zip(alice_verify, bob_verify) if a[1] != b[1])

# Calculate the error rate
error_rate = error_count / verification_size

print("Error Rate:", error_rate)


TypeError: Invalid operand types

f)

In [5]:
def Eve(events, error_rate=0.25):
    results = []
    for event in events:
        index, state = event
        # Introduce a controlled error based on the specified error rate
        if np.random.rand() < error_rate:
            # Flip the guessed bit with 50% probability
            guessed_state = qt.basis(2, 1 - state.argmax())
        else:
            # Perform the same measurement as Bob
            measurement = qt.expect([qt.basis(2, 0), qt.basis(2, 1)], state)
            # Find the index of the maximum expectation value
            max_index = np.argmax(measurement)
            # Eve makes her best guess based on the measurement
            guessed_state = qt.basis(2, max_index)
        results.append([index, guessed_state])
    return results


In [6]:
def Bob(events, error_rate=0.25):
    results = []
    for event in events:
        index, state = event
        
        # Introduce a controlled error based on the specified error rate
        if np.random.rand() < error_rate:
            # Flip the guessed bit with 50% probability
            guessed_bit = 1 - state.argmax()
        else:
            # Bob performs the same measurement as before
            measurement = state.measure([qt.basis(2, 0), qt.basis(2, 1)])
            if measurement[0] == 1:
                guessed_bit = 0
            elif measurement[1] == 1:
                guessed_bit = 1
                
        results.append([index, guessed_bit])
    return results


In [7]:
def Eve(events):
    results = []
    for event in events:
        index, state = event
        # Eve randomly chooses a guessed state
        guessed_state = qt.basis(2, np.random.choice([0, 1]))
        results.append([index, guessed_state])
    return results


In [18]:
Np = 1000  # Increase Np for better statistics

# Alice sends photons to Bob through the channel
alice_events = Alice(Np)

# Eve randomly guesses the states
eve_output = Eve(alice_events)

# Bob receives and measures the photons
bob_output = Bob(eve_output)

# Alice and Bob use half of the events for verification
verification_size = Np // 2
alice_verify = alice_events[:verification_size]
bob_verify = bob_output[:verification_size]

# Count the number of errors in the verification process
error_count = sum(1 for a, b in zip(alice_verify, bob_verify) if a[1] != b[1])

# Calculate the error rate
error_rate = error_count / verification_size

print("Error Rate:", error_rate)


TypeError: Invalid operand types

In [15]:
import numpy as np
from qutip import Qobj

# Define the quantum states
zero_state = Qobj([[1], [0]])  # |↔⟩
one_state = Qobj([[0], [1]])  # |⤢⟩

def Alice(Np):
    np.random.seed(0)
    bits = np.random.randint(2, size=Np)
    states = [zero_state if bit == 0 else one_state for bit in bits]
    return list(enumerate(states, start=1))

def Bob(Alice_output):
    clicks = []
    for i, state in Alice_output:
        measurement = state.dag() * state
        if measurement[0, 0] == 1:  # Bob's detector clicks
            bit = 0 if state == zero_state else 1
            clicks.append((i, bit))
    return clicks

def Eve(Alice_output):
    # Eve performs the same measurement as Bob
    return Bob(Alice_output)

def error_rate(Alice_output, Bob_output):
    Np = len(Alice_output)
    N = len(Bob_output)
    errors = sum(Alice_output[i-1][1] != bit for i, bit in Bob_output)
    return errors / Np

# Simulate the protocol
Np = 100
Alice_output = Alice(Np)
Eve_output = Eve(Alice_output)
Bob_output = Bob(Eve_output)

# Calculate the error rate
print(f"Error rate: {error_rate(Alice_output, Bob_output)}")


AttributeError: 'int' object has no attribute 'dag'

In [16]:
import numpy as np
from qutip import basis, Qobj

def alice(Np):
    events = []
    for i in range(1, Np+1):
        # Randomly choose 0 or 1 with equal probability
        bit = np.random.choice([0, 1])
        # Create a qubit in H/V basis
        photon_state = basis(2, bit)
        events.append([i, photon_state])
    return events

def bob(alice_output):
    accepted_events = []
    for event in alice_output:
        # Bob randomly chooses between |↕⟩ and |⤡⟩
        bob_polarizer = np.random.choice([basis(2, 0), basis(2, 1)])
        # Measure the photon with the chosen polarizer
        measurement = event[1].overlap(bob_polarizer)
        if measurement != 0:
            # If Bob gets a click, record the event index and the bit he thinks Alice sent
            accepted_events.append([event[0], int(measurement)])
    return accepted_events

def generate_private_key(Np):
    alice_output = alice(Np)
    bob_output = bob(alice_output)
    
    # Use 1/2 of the accepted events for verification
    num_verification_events = len(bob_output) // 2
    verification_events = bob_output[:num_verification_events]
    remaining_events = bob_output[num_verification_events:]
    
    # Verify the channel using 1/2 of the accepted events
    verification_passed = all([event[1] == alice_output[event[0]-1][1].nonzero()[1][0] for event in verification_events])
    
    # Generate private key using the remaining accepted events
    private_key = [event[1] for event in remaining_events]
    
    return private_key, verification_passed

# Example usage with 100 photons
private_key, verification_passed = generate_private_key(100)

print("Private Key:", private_key)
print("Channel Verification Passed:", verification_passed)


ValueError: a must be 1-dimensional

In [17]:
import numpy as np
import qutip as qt

def Alice(Np):
    events = []
    for i in range(1, Np + 1):
        bit_to_send = np.random.choice([0, 1])
        if bit_to_send == 0:
            photon_state = qt.basis(2, 0)  # |↔⟩
        else:
            photon_state = qt.basis(2, 1)  # |⤢⟩
        events.append([i, photon_state])
    return events

def Bob(events):
    clicks = []
    for event in events:
        event_number, photon_state = event
        # Bob randomly chooses to measure with |↕⟩ or |⤡⟩
        measurement_basis = qt.basis(2, np.random.choice([0, 1]))
        probability_of_click = abs(qt.expect(measurement_basis, photon_state))**2

        if np.random.rand() < probability_of_click:
            # Bob gets a click, and he infers the bit sent by Alice
            inferred_bit = 0 if measurement_basis == qt.basis(2, 0) else 1
            clicks.append([event_number, inferred_bit])

    return clicks

# Simulation parameters
Np = 10  # Number of bits (photons) sent by Alice

# Alice sends photons
alice_events = Alice(Np)

# Bob measures photons and infers bits
bob_results = Bob(alice_events)

# Print results
print("Alice's sent photons:")
for event in alice_events:
    print(f"Event {event[0]}: {event[1]}")

print("\nBob's inferred bits:")
for result in bob_results:
    print(f"Event {result[0]}: Bob infers bit {result[1]}")


TypeError: Invalid operand types